
API_SERVER = 'https://api.sd2e.org'
API_TOKEN = ''
MONGODB_HOST = 'catalog.sd2e.org'
MONGODB_PORT = 27020
MONGODB_DATABASE = 'catalog'
MONGODB_AUTH_DATABASE = 'admin'
MONGODB_REPLICA_SET = 'rs0'
MONGODB_USERNAME = 'readonly'
MONGODB_PASSWORD = ''
PAGESIZE = 20
STORAGE_SYSTEM = 'data-sd2e-community'
REACTOR_MESSAGE_SYNC = True
JOB_MANAGER_ID = 'jobs-manager.prod'
JOB_MANAGER_NONCE = 'SD2E_z00EbBOeoYJry'
JOB_INDEXER_ID = 'jobs-indexer.prod'
JOB_INDEXER_NONCE = 'SD2E_RyZRVDMgXK1DV'
