
API_SERVER = 'https://api.sd2e.org'
API_TOKEN = ''
MONGODB_HOST = 'catalog.sd2e.org'
MONGODB_PORT = 27020
MONGODB_DATABASE = 'catalog'
MONGODB_AUTH_DATABASE = 'admin'
MONGODB_REPLICA_SET = 'rs0'
MONGODB_USERNAME = 'readonly'
MONGODB_PASSWORD = ''
PAGESIZE = 20
